### ISSUE TITLE
NativeGasEstimator sometimes returns invalid values

### ISSUE THREAD

**Issue by sunce86** [gnosis/gp-gas-estimation#25]
Invalid values reported here https://github.com/gnosis/gp-v2-services/issues/1607

Rule `max_fee_per_gas >= base_fee_per_gas` is violated.

**Comment by sunce86** [comment]
Here is the complete result for one of the failing logs:
`(time_limit, EstimatedGasPrice)`

(1.0, EstimatedGasPrice { legacy: 0.0, eip1559: Some(GasPrice1559 { base_fee_per_gas: 253655239941.0, max_fee_per_gas: 255655239941.0, max_priority_fee_per_gas: 2000000000.0 }) }), 

(2.0, EstimatedGasPrice { legacy: 0.0, eip1559: Some(GasPrice1559 { base_fee_per_gas: 253655239941.0, max_fee_per_gas: 255655239941.0, max_priority_fee_per_gas: 2000000000.0 }) }), 

(4.0, EstimatedGasPrice { legacy: 0.0, eip1559: Some(GasPrice1559 { base_fee_per_gas: 253655239941.0, max_fee_per_gas: 255655239941.0, max_priority_fee_per_gas: 2000000000.0 }) }), 

(8.0, EstimatedGasPrice { legacy: 0.0, eip1559: Some(GasPrice1559 { base_fee_per_gas: 253655239941.0, max_fee_per_gas: 161020051729.65442, max_priority_fee_per_gas: 2000000000.0 }) }), 

(16.0, EstimatedGasPrice { legacy: 0.0, eip1559: Some(GasPrice1559 { base_fee_per_gas: 253655239941.0, max_fee_per_gas: 122138446270.20798, max_priority_fee_per_gas: 3279681565.862953 }) }), 

(32.0, EstimatedGasPrice { legacy: 0.0, eip1559: Some(GasPrice1559 { base_fee_per_gas: 253655239941.0, max_fee_per_gas: 122138446270.20798, max_priority_fee_per_gas: 3860950464.669117 }) }), 

(64.0, EstimatedGasPrice { legacy: 0.0, eip1559: Some(GasPrice1559 { base_fee_per_gas: 253655239941.0, max_fee_per_gas: 122138446270.20798, max_priority_fee_per_gas: 3376304794.1242065 }) }), 

(128.0, EstimatedGasPrice { legacy: 0.0, eip1559: Some(GasPrice1559 { base_fee_per_gas: 253655239941.0, max_fee_per_gas: 122138446270.20798, max_priority_fee_per_gas: 2000000000.0 }) })]

Why native gas price estimator breaks the rule `max_fee_per_gas >= base_fee_per_gas` is because:
1. Driver `target_confirm_time` parameter is set to 30s (in our case it seeks for a result between `time_limit = 16.0` and `time_limit = 32.0`.
2. `max_fee_per_gas` is much lower because above calculation is done for block 14116100, and it's parent block had 8 previous 100% full blocks causing the sudden surge in `base_fee_per_gas` (check previous blocks for https://etherscan.io/block/14116099). In this cases, algorithm lags with increasing the `max_fee_per_gas`, because there is a high probability that, after 8 full blocks, and in a 30s timeframe from now, `base_fee_per_gas` will drop significantly and our tx will be included.

Based on this analysis I would say that algorithm works as expected, so I would just lower the `target_confirm_time` from 30s to <8s

**Comment by vkgnosis** [comment]
The algorithm is supposed to give us reasonable parameters for the transaction to be included within 30 seconds. Lowering this target to 8s doesn't make sense to me as that could with some other algorithms give unreasonable aggressive (expensive) results. 

What would be most correct from our pov is that nodes shouldn't reject our transaction because we expect the gas price to go down so our max_fee is actually acceptable. Since we cannot influence this we have a few ways to solve this:
- change this algorithm here to be more conservative with the max fee.
- when returning a result set max_fee to be at least base_fee
- in services we could skip the current run loop if we detect that the condition has been violated as that means the gas price has changed quickly and it could be better to try again after a short time
- in services use higher max_fee for the simulations

I think the last point makes the most sense and is a more fine grained fix because for simulations the exact gas price shouldn't be important. We could also change the submission logic of the actual transaction to detect rejection because of this error and in that case keep trying for a bit but not sure if that is necessary yet.

**Comment by sunce86** [comment]
Lets try with the variation of `when returning a result set max_fee to be at least base_fee`: https://github.com/gnosis/gp-gas-estimation/pull/27
